### ISSUE TITLE
Consider changing onmouseup action to something else in DatePicker radio buttons

### ISSUE THREAD

**Issue by krezovic** [dojo/widgets#532] opened 2018-04-02 19:55 UTC
**Bug**

Package Version: RC1

Trying to use Calendar in MSIE 11, with the theme from @dojo/themes. Thing is, MSIE 11 does not support appearance property, so the current "trick" used in the theme that works on all other browsers won't work there.

And if I set radio button to disabled via CSS, it never gets onmouseup event, but does get onchange event due to clicking on the label, which is currently being used. That results in Year/Month dropdown never being closed, and calendar being rendered buggy.

I've tried to move the function call from onmouseup event into onchange handler, and it seems to work here. Not sure why is onmouseup being used, but I guess there's a good reason.

Please provide a solution that will also work on IE11 with hidden radio button as in @dojo/themes (with something other than css:appearance property).

**Comment by smhigley** [comment] 2018-04-09 19:55
Can't reproduce on IE11 after adding `opacity: 0` to the radio inputs. It cannot close on the `onChange` event, since that would result in the menu being closed every time a keyboard user arrowed to a new month or year.

There are two other issues with the Calendar, which might be obfuscating the issue:
1. IE11 styling problems, issue here: https://github.com/dojo/themes/issues/16
2. Cross-browser menu bugs, issue here: #535 

Closing this issue for now, but feel free to reopen if the IE11 bug is still present after the above issues are resolved.

**Closed by smhigley** 2018-04-09 19:55 UTC
