### ISSUE TITLE
Widget control for this.children

### ISSUE THREAD

**Issue by smhigley** [dojo/widgets#125] opened 2017-04-23 21:45 UTC
Widget control patterns work well for widgets that internally create their own children based on properties, but for widgets like Menu (or possibly dgrid?) that can support large, complex child structures, it's a better authoring experience to use the children array.

For example, this menu creation pattern feels intuitive:
```javascript
w(Menu, {
   ...menu props
}, [
   w(MenuItem, <MenuItemProperties> {
      key: 'menu-item-1',
      ... other props
   }, [ 'Text Label' ]),
   w(MenuItem, <MenuItemProperties> {
      key: 'menu-item-2',
      ... other props
   }, [
      'Text Label 2',
      w(Menu, {
         hidden: this.state.menuHidden,
         onRequestHide: () => {
            this.setState({ menuHidden: true });
         },
         onRequestShow: () => {
            this.setState({ menuHidden: false });
         }
      }, [
         w(MenuItem, { ... }),
         w(MenuItem, { ... })
      ])
   ]),
   ... etc
])
```
But this feels clunky:
```javascript
w(Menu, {
   structure: [
      {
         label: 'Menu Item',
         ... other props
      },
      {
         label: 'Menu Item 2',
         dropdownMenu: {
            ... menu props,
            structure: [
               { label: 'foo' },
               { label: 'bar' }
            ]
         }
      },
      {
         label: 'Menu Item 3',
         href: '#nowhere'
      }
   ]
})
```

For widgets like Dialog and SlidePane the first example would be fine as-is, since they don't need to control their children. The problem is widgets like Menu that need to control some of their children's properties. For example, for those dropdown menus to work correctly, the Menu Item and associated dropdown need to have certain properties (e.g. `aria-controls`, `aria-expanded`) set correctly and synchronized between the two, as well as focus changing handled between menu items. This is currently only possible if Menu creates all its children internally.

In the Menu PR, @mwistrand creates a part-solution by controlling child properties by iterating through `this.children`. It breaks down if someone wishes to create a custom node structure by wrapping `w(MenuItem)` in `v('li')`, which I think should be possible.

Would it be possible to provide some way for parent widgets to be aware of specified children? Are there any other widget authoring patterns that would create a good user experience while also allowing widgets with complex user-determined internal structures to control their children?

**Comment by agubler** [comment] 2017-04-24 10:30
So my thoughts are:

For the `menu` I don't think, at least initially that it should actually support custom nodes being injected into the structure. The point of the menu to be prescriptive regarding structure and support "hard" things like focus, a11y, sub-menus etc out of the box.

In principle I don't have a problem with decorating children and I think for widgets like `menu` it might be the only way (if we want to use the children argument to construct them); The problem is that we cannot specify an API to ensure that the `child` widgets are the correct type (or have support for the correct properties).

TS2.3 will actually help with that, to allow us to accept static type information for widget's children and infer the type when using `w` - but allow us to default to accepting any Dojo 2 widget.

Potential changes to [`widget-core`](https://github.com/dojo/widget-core/compare/master...agubler:ts-2.3) will enable typings like so the type of the child can be guaranteed.

<img width="703" alt="d_ts_-_widget-core" src="https://cloud.githubusercontent.com/assets/1982678/25331310/72c1f3c8-28da-11e7-9d96-68b1e1d727f9.png">

**Comment by bitpshr** [comment] 2017-10-23 18:57
The story around controlling widget children isn't great, but it works decently enough, especially with 2.3's introduction of typed children. Many components (TabController, ComboBox, AccordionPane, Menu) iterate over children and `assign` new properties as necessary. These components that depend on a specific type of child or a specific child structure should be explicit about the children they accept using proper typings. Arbitrary child DOM, like wrapping a child in an `<li>`, just wouldn't be supported out of the box and would require extension.

I think we can close this now that we've absorbed the good point that @smhigley brought up.

**Closed by bitpshr** 2017-10-23 18:57 UTC
Labels: beta4, discussion
