### ISSUE TITLE
Text widget

### ISSUE THREAD

**Issue by rorticus** [dojo/widgets#1647] opened 2021-01-21 16:18 UTC
It would be great to have a Text widget for creating consistent styled text without having to use CSS every time. This will make theming your application even easier.

Example usage,

```tsx
<Text size="h1">Heading</Text>
<Text style="success">Some lovely green text</Text>
```

You should be able to specify the size (i.e., header, subheader, normal body text, label text, etc) as well as a style like "success", "alert", etc.

**Comment by tomdye** [comment] 2021-03-22 16:00
This is related to duplicate of https://github.com/dojo/widgets/issues/1564

**Closed** 2021-06-01 12:53 UTC
